"""empty message

Revision ID: 8e536a77aae4
Revises: 
Create Date: 2020-09-15 10:09:14.320195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e536a77aae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kinda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindas', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('pwd', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keeper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('kid', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kid'], ['kinda.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keeper')
    op.drop_table('user')
    op.drop_table('kinda')
    # ### end Alembic commands ###
